### ISSUE TITLE
As a user, I want to select a document to share via a temporary web link

### ISSUE THREAD

**Issue by Matanatr96** [BranSeal/HealthPort#41]
## Story/Task Details
- [ ] Task1
- [ ] Task2
- [ ] Task3

### Scenario 1: The user wants to select a document to share via temporary link
- Given the user is viewing the dashboard;
- When the user selects a document and selects to share via link;
- Then the application pulls up the share link page.

## Done Done Criteria
- [ ] All unit tests have passed
- [ ] Code review completed
- [ ] Merge reviewed and passing code to master branch
