### ISSUE TITLE
As a user, I want to delete a profile so that it is no longer on my account.

### ISSUE THREAD

**Issue by BranSeal** [BranSeal/HealthPort#43]
## Story/Task Details
- [ ] Update database
- [ ] Delete Confirmation Pop-Up UI

### Scenario 1: A user wants to remove a profile from her account and enters valid password.
- Given the user is on the edit profile page;
- When she selects "Delete", enters a valid password and the profile’s name, and selects "Confirm";
- Then the system will successfully remove the profile from the account.
### Scenario 2: A user wants to remove a profile from her account and enters invalid password or profile name.
- Given: the user is on her edit profile page;
- When: she selects "Delete", enters an invalid password or profile name, and selects "Confirm";
- Then: the system notifies the user that she has entered invalid information and cancels the deletion of profile.
### Scenario 3: A user wants to cancel the deletion of a profile.
- Given: the user is on the edit profile page and selects "Delete";
- When: she selects "Cancel";
- Then: the system will cancel the deletion of a profile and take the user back to the dashboard.

## Done Done Criteria
- [ ] All unit tests have passed
- [ ] Code review completed
- [ ] Merge reviewed and passing code to master branch
